NAME =  RPN

CFLAGS = -Wall -Wextra -Werror -std=c++98

SRC = RPN.cpp \
	  main.cpp \

HDRS = RPN.hpp \

OBJ = $(SRC:.cpp=.o)

all : $(NAME) 

$(NAME): $(OBJ) $(HDRS)
	@c++ $(FLAGS) $(OBJ) -o $@
	@echo "\033[0;36m ⚙️  MakeFile ⚙️ : ✅ COMPILED SUCCESSFULY\033[0m"

%.o:%.cpp		
		@c++ $(CFLAGS) -o $@ -c $<
clean :
	@rm -f $(OBJ)
	@echo "\033[0;36m ⚙️  MakeFile ⚙️ : 🗑️ Objects removed!033[0m"
fclean : clean
	@rm -f $(NAME)
	@echo "\033[0;36m ⚙️  MakeFile ⚙️ : 🗑️ CLEANED SUCCESSFULY\033[0m"

re: fclean all

.PHONY : all clean fclean re